homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 186 
  unit_system: metric
  time_zone: Africa/Johannesburg
  customize: !include customize.yaml
  packages: !include_dir_named packages

zone: !include zones.yaml

frontend:
  themes: !include_dir_merge_named themes/

config:

http:
  api_password: !secret http_password
  base_url: !secret ha_url
  ssl_certificate: "/ssl/fullchain.pem"
  ssl_key: "/ssl/privkey.pem"

updater:
discovery:
conversation:
history:
logbook:
map:
sun:
ios:

tts:
  - platform: google

cloud:

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml