homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 186 
  unit_system: metric
  time_zone: Africa/Johannesburg
  customize: !include customize.yaml
  packages: !include_dir_named packages

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: homeassistant

zone: !include zones.yaml

frontend: !include frontend.yaml

config:

http:
  # base_url: !secret ha_url
  ssl_certificate: "/ssl/fullchain.pem"
  ssl_key: "/ssl/privkey.pem"

logger:
  default: warn

hacs:
  token: !secret github_hacs_token

updater:
discovery:
conversation:
history:
logbook:
map:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state

# tts:
#   - platform: google_translate
#     cache: true
#     cache_dir: /tmp/tts
#     time_memory: 300
#     base_url: http://192.168.1.32:8123
#     service_name: google_say

shopping_list:

lovelace:
  mode: yaml
  resources:
    - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
      type: module
    - url: /local/plugins/card-tools.js?v=1
      type: js
    - url: /local/plugins/card-mod.js?v=1
      type: module
    - url: /local/plugins/time-input-row.js?v=0.0.1
      type: js
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
      

recorder:
  purge_keep_days: 5
  auto_purge: true

mobile_app: