homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 186 
  unit_system: metric
  time_zone: Africa/Johannesburg
  customize: !include customize.yaml
  packages: !include_dir_named packages

zone: !include zones.yaml

frontend: !include frontend.yaml
# panel_custom: !include panel_custom.yaml
# binary_sensor:
#   - platform: mqtt
#     state_topic: dummy/floorplan/sensor
#     name: Floorplan

config:

http:
  api_password: !secret http_password
  base_url: !secret ha_url
  ssl_certificate: "/ssl/fullchain.pem"
  ssl_key: "/ssl/privkey.pem"

logger:
  default: warn

updater:
discovery:
conversation:
history:
logbook:
map:
ios:

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://192.168.1.32:8123
    service_name: google_say

cloud:

shopping_list:

lovelace:
  mode: yaml

recorder:
  purge_keep_days: 5
  purge_interval: 1

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password