#    _____
#   / ___/___  ____  _________  __________
#   \__ \/ _ \/ __ \/ ___/ __ \/ ___/ ___/
#  ___/ /  __/ / / (__  ) /_/ / /  (__  )
# /____/\___/_/ /_/____/\____/_/  /____/


sensor:
  - platform: yr
  
  - platform: openweathermap
    api_key: !secret own_api_key
    monitored_conditions:
      - weather
      - temperature
      - humidity
      - rain
      - clouds

  - platform: darksky
    api_key: !secret dark_sky_key
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - precip_probability
      # - wind_speed
      # - cloud_cover
      - icon
      - temperature_min
      - temperature_max
      - daily_summary
      - hourly_summary
      # - nearest_storm_distance
      # - precip_type
      # - precip_intensity
      - temperature
      # - apparent_temperature
      # - dew_point
      # - wind_bearing
      # - humidity
      # - pressure
      # - visibility
      # - ozone
      # - minutely_summary

  - platform: season

  - platform: template
    sensors:
      forecast_0:
        friendly_name: "Today"
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.png'}}

      forecast_1:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
          {{ date | timestamp_custom("%A - %d %B") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_1.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_1.state ~ '.png'}}

      forecast_2:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
          {{ date | timestamp_custom("%A - %d %B") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_2.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_2.state ~ '.png'}}

      forecast_3:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
          {{ date | timestamp_custom("%A - %d %B") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_3.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_3.state ~ '.png'}}

      forecast_4:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
          {{ date | timestamp_custom("%A - %d %B") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_4.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_4.state ~ '.png'}}

      forecast_5:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
          {{ date | timestamp_custom("%A - %d %B") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_5.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_5.state ~ '.png'}}

      forecast_6:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
          {{ date | timestamp_custom("%A - %d %B") }}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_6.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_6.state ~ '.png'}}

      forecast_7:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (7 * 86400 ) -%}
          {{ date | timestamp_custom("%A - %d %B") }}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_7.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_7.state ~ '.png'}}

#    ______
#   / ____/___ _____ ___  ___  _________ ______
#  / /   / __ `/ __ `__ \/ _ \/ ___/ __ `/ ___/
# / /___/ /_/ / / / / / /  __/ /  / /_/ (__  )
# \____/\__,_/_/ /_/ /_/\___/_/   \__,_/____/


camera:
  - platform: generic
    name: weather_map
    still_image_url: https://www.yr.no/place/South_Africa/KwaZulu-Natal/Durban/meteogram.svg
    content_type: 'image/svg+xml'

#    ______
#   / ____/________  __  ______  _____
#  / / __/ ___/ __ \/ / / / __ \/ ___/
# / /_/ / /  / /_/ / /_/ / /_/ (__  )
# \____/_/   \____/\__,_/ .___/____/
#                      /_/

group:
  weather_card_forecast:
    name: Forecast
    view: no
    icon: mdi:sun
    entities:
      - sensor.forecast_0
      - sensor.forecast_1
      - sensor.forecast_2
      - sensor.forecast_3
      - sensor.forecast_4
      - sensor.forecast_5
      - sensor.forecast_6
      - sensor.forecast_7

  current_weather:
    name: Current Weather
    view: no
    entities:
      - sensor.owm_temperature
      - sensor.owm_condition
      - sensor.owm_cloud_coverage
      - sensor.owm_humidity
      - sensor.owm_rain