#    _____
#   / ___/___  ____  _________  __________
#   \__ \/ _ \/ __ \/ ___/ __ \/ ___/ ___/
#  ___/ /  __/ / / (__  ) /_/ / /  (__  )
# /____/\___/_/ /_/____/\____/_/  /____/


weather:      
  - platform: darksky
    api_key: !secret dark_sky_key
    mode: daily
    
sun:

sensor:
  - platform: season
