automation:
- id: hass_theme_boot
  alias: Set Theme
  initial_state: 'on'
  trigger:
    - platform: homeassistant 
      event: start
  action:
  - service: frontend.set_theme
    data_template:
      name: slate