###########################################################################################################
#     _   __     __                      __                      __   _____            __                 #
#    / | / /__  / /__      ______  _____/ /__   ____ _____  ____/ /  / ___/__  _______/ /____  ____ ___   #
#   /  |/ / _ \/ __/ | /| / / __ \/ ___/ //_/  / __ `/ __ \/ __  /   \__ \/ / / / ___/ __/ _ \/ __ `__ \  #
#  / /|  /  __/ /_ | |/ |/ / /_/ / /  / ,<    / /_/ / / / / /_/ /   ___/ / /_/ (__  ) /_/  __/ / / / / /  #
# /_/ |_/\___/\__/ |__/|__/\____/_/  /_/|_|   \__,_/_/ /_/\__,_/   /____/\__, /____/\__/\___/_/ /_/ /_/   #
#                                                                       /____/                            #
###########################################################################################################

#########################    OBJECTS    #########################

system_health:

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

asuswrt:
  host: 192.168.1.1
  username: !secret router_username
  password: !secret router_password

device_tracker:
  - platform: asuswrt

namecheapdns:
  domain: !secret namecheap_tld
  password: !secret namecheap_password

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
      - type: last_boot

  - platform: nut
    alias: server_ups
    resources:
      - battery.charge
      - battery.voltage
      - input.frequency
      - input.voltage
      - output.voltage
      - ups.load

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 14204 # Palo Alto speedtest server
  manual: true

# xiaomi_aqara:
#   gateways:
#     - host: 192.168.1.51
#       mac: !secret xiaomi_gateway_mac
#       key: !secret xiaomi_gateway_password

group:
  sys_status:
    name: System Status
    entities:
      - sensor.memory_free
      - sensor.disk_use_percent_home
      - sensor.processor_use
      - sensor.last_boot

  network:
    name: Network
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload

input_boolean:
  booted:
    name: Booted
    initial: off


#########################    AUTOMATIONS    #########################

automation:

  - id: letsencrypt-renewal
    alias: 'LetsEncrypt renewal'
    trigger:
    - platform: time
      at: '00:00:00'
    action:
    - service: hassio.addon_stop
      data:
        addon: core_nginx_proxy
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt
    - delay: '00:01:30'
    - service: hassio.addon_start
      data:
        addon: core_nginx_proxy
        
  - id: 6BFB2009-CE8C-452F-9984-128342F8FD56
    alias: Run Speedtest when PC and tv are both off
    initial_state: 'on'
    trigger:
      platform: time_pattern
      minutes: '/60'
      seconds: 0
    condition:
      - condition: template
        value_template: >-
          {%if states('sensor.rt_ac53_kbyte_sec_received') | float > 12 %}
            False
          {% else %} 
            True
          {% endif %} 
    action:
      - service: speedtestdotnet.speedtest

  - id: F49BB5E9-0F39-4585-9D47-011A76A6AFAE
    alias: 'booted'
    initial_state: 'on'
    trigger:
    - event: start
      platform: homeassistant
    condition: []
    action:
    - service: input_boolean.turn_off 
      data:
        entity_id: input_boolean.booted
    - delay: '00:00:30'
    - service: input_boolean.turn_on 
      data:
        entity_id: input_boolean.booted
