###########################################################################################################
#     _   __     __                      __                      __   _____            __                 #
#    / | / /__  / /__      ______  _____/ /__   ____ _____  ____/ /  / ___/__  _______/ /____  ____ ___   #
#   /  |/ / _ \/ __/ | /| / / __ \/ ___/ //_/  / __ `/ __ \/ __  /   \__ \/ / / / ___/ __/ _ \/ __ `__ \  #
#  / /|  /  __/ /_ | |/ |/ / /_/ / /  / ,<    / /_/ / / / / /_/ /   ___/ / /_/ (__  ) /_/  __/ / / / / /  #
# /_/ |_/\___/\__/ |__/|__/\____/_/  /_/|_|   \__,_/_/ /_/\__,_/   /____/\__, /____/\__/\___/_/ /_/ /_/   #
#                                                                       /____/                            #
###########################################################################################################

#########################    OBJECTS    #########################

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
      - type: since_last_boot

  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    server_id: 10385 # washington speedtest server
    manual: true

xiaomi_aqara:
  gateways:
    - host: 192.168.1.51
      mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_password
      # discovery_retry: 10

group:
  sys_status:
    name: System Status
    entities:
      - sensor.memory_free
      - sensor.disk_use_percent_home
      - sensor.processor_use
      - sensor.since_last_boot

  network:
    name: Network
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload


#########################    AUTOMATIONS    #########################

automation:

  - id: 6BFB2009-CE8C-452F-9984-128342F8FD56
    alias: Run Speedtest when PC and computer are both off
    initial_state: 'on'
    trigger:
      platform: time
      minutes: '/60'
      seconds: 0
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.power_pc
        state: 'off'
      - condition: state
        entity_id: media_player.samsung_tv_remote
        state: 'off'
    action:
      - service: sensor.update_speedtest

  - id: 28677636-CB69-4157-AEEE-9CE6CD589063
    alias: 'Battery Alert'
    initial_state: 'on'
    trigger:
      - platform: time
        at: '10:00:00'
      - platform: time
        at: '18:00:00'
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: >-
            {%- set threshold = 40 -%}
            {%- for item in states.switch if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown")) -%}
            {%- if loop.first -%}
            {{ true }}
            {%- endif -%}
            {%- endfor -%}
        - condition: template
          value_template: >-
            {%- set threshold = 40 -%}
            {%- for item in states.sensor if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low")) -%}
            {%- if loop.first -%}
            {{ true }}
            {%- endif -%}
            {%- endfor -%}
        - condition: template
          value_template: >-
            {%- set threshold = 40 -%}
            {%- for item in states.binary_sensor if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown")) -%}
            {%- if loop.first -%}
            {{ true }}
            {%- endif -%}
            {%- endfor -%}
    action:
      - service: notify.p_phone_telegram
        data_template:
          message: >-
            {%- set threshold = 40 -%}
            {%- set domains = [states.switch, states.sensor, states.binary_sensor ] -%}
            {%- for domain in domains -%}
            {%- if loop.first -%}
            The following devices have low battery levels:
            {%- endif -%}
            {%- for item in domain if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown")) -%}
            {%- if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) %}
            {{ item.name }} ({{ item.attributes['battery_level'] }}),
            {% endif -%}
            {%- if "battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown") -%}
            {{ item.name }} ({{ item.state }}),
            {% endif -%}
            {%- endfor -%}
            {%- endfor -%}

#########################    CUSTOMIZATION    #########################

homeassistant:
  customize:
    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:speedometer
    sensor.speedtest_download:
      friendly_name: Download
      icon: mdi:download
    sensor.speedtest_upload:
      friendly_name: Upload
      icon: mdi:upload