          ###################################################
          #     ____           __                           #
          #    / __ )___  ____/ /________  ____  ____ ___   #
          #   / __  / _ \/ __  / ___/ __ \/ __ \/ __ `__ \  #
          #  / /_/ /  __/ /_/ / /  / /_/ / /_/ / / / / / /  #
          # /_____/\___/\__,_/_/   \____/\____/_/ /_/ /_/   #
          #                                                 #
          ###################################################

#########################    OBJECTS    #########################

yeelight:
  devices:
    192.168.1.36:
      name: bedroom_ceiling
      save_on_change: false
      use_music_mode: false
    192.168.1.52:
      name: bedside
      save_on_change: false
      use_music_mode: false
  custom_effects:
    - name: 'Sunrise'
      flow_params:
        count: 1
        action: stay
        transitions:
          - RGBTransition: [255, 0, 0, 2000, 1]
          - TemperatureTransition: [1700, 180000, 10]
          - TemperatureTransition: [1800, 180000, 15]
          - TemperatureTransition: [2000, 180000, 30]
          - TemperatureTransition: [2200, 180000, 60]
          - TemperatureTransition: [2500, 180000, 100]

light:
  - platform: group
    name: bedroom
    entities:
      - light.bedroom_ceiling
      - light.bedside

climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 9001
    controller_data: 192.168.1.53

switch:
  - platform: broadlink
    host: 192.168.1.53
    mac: !secret mac_bedroom_rm_mini

#########################    VARIABLES    #########################

input_boolean:
  
  bedroom_dim:
    name: bedroom brightness control
    initial: 'off'

input_select:
  bedroom_scene:
    name: Bedroom Scene
    options:
      - bedroom_moon
      - bedroom_flame
      - bedroom_tree
      - bedroom_water
    initial: bedroom_moon
    icon: mdi:theme-light-dark


#########################    SCENES    #########################

scene:
  - name: bedroom_moon
    entities:
      light.bedroom:
        state: on
        rgb_color: [255,177,110]
        brightness: 255

  - name: bedroom_flame
    entities:
      light.bedroom:
        state: on
        rgb_color: [255, 0, 27]
        brightness: 76

  - name: bedroom_tree
    entities:
      light.bedroom:
        state: on
        rgb_color: [0, 255, 0]
        brightness: 255

  - name: bedroom_water
    entities:
      light.bedroom:
        state: on
        rgb_color: [0, 0, 255]
        brightness: 255

  - name: bedroom_off
    entities:
      light.bedroom: off

  - name: bedroom_low
    entities:
      light.bedroom:
        state: on
        brightness_pct: 20

  - name: bedroom_medium
    entities:
      light.bedroom:
        state: on
        brightness_pct: 60

  - name: bedroom_high
    entities:
      light.bedroom:
        state: on
        brightness_pct: 100

#########################    AUTOMATIONS    #########################

automation:

        ##### Wall Switch #####

  - id: 749F1474-272C-4742-94D1-0536408AF3C4
    alias: bedroom wall off
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedroom_wall
        click_type: single
    condition:
    - condition: state
      entity_id: light.bedroom
      state: 'on'
    action:
    - service: light.turn_off
      entity_id: light.bedroom

  - id: F24FF9B4-3DD1-40D3-9231-84A0D1654B32
    alias: bedroom wall on before bedtime
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedroom_wall
        click_type: single
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: light.bedroom
        state: 'off'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
    action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness_pct: 100
        rgb_color: [255,177,110]
    
  - id: 96308D96-0626-4EAC-9A5F-F02E9D9A430D
    alias: bedroom wall on after bedtime
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedroom_wall
        click_type: single
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: light.bedroom
        state: 'off'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
    action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness_pct: 30
        rgb_color: [255,0,0]
    
        ##### Button - Single Press #####

  - id: 854CFDDC-4FBC-4AAD-8FE4-8FC7C6BE464B
    alias: Bedroom button off
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedside_button
        click_type: single
    condition:
    - condition: state
      entity_id: light.bedroom
      state: 'on'
    action:
    - service: light.turn_off
      entity_id: light.bedroom

  - id: AD49B25E-B89C-406E-B8FB-E1AE3B3F5735
    alias: bedroom button on before bedtime
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedside_button
        click_type: single
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
      - condition: state
        entity_id: light.bedroom
        state: 'off'
    action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness_pct: 100
        rgb_color: [255,177,110] 

  - id: 1DED1273-CE29-40A0-ADFA-24E921BDA222
    alias: bedroom button on after bedtime
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedside_button
        click_type: single
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
      - condition: state
        entity_id: light.bedroom
        state: 'off'
    action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        brightness_pct: 20
        rgb_color: [255,0,0]

        ##### Button - Double Press #####

  - id: F81CB052-5F67-4D76-9ADB-6F93F31EE2C4
    alias: Bedroom double switch
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.bedside_button
          click_type: double
    condition:
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          brightness: 50
      - service: input_select.select_option
        data:
          entity_id: input_select.bedroom_scene
          option: "bedroom_flame"
      - service: script.turn_on
        entity_id: script.bedtime

  - id: 4F71CC4A-2392-4651-9F79-B76FE8B1BCA0
    alias: Bedroom double switch
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.bedside_button
          click_type: double
    condition:
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bedtime

        ##### Button - Long Press #####

  - id: 25FA631C-2541-44CD-9BC4-DD6E5DF4A88B
    alias: Bedroom Scene Change
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.bedside_button
          click_type: long_click_press
    condition:
      - condition: state
        entity_id: light.bedroom
        state: 'on'
    action:
      - service: input_select.select_next
        entity_id: input_select.bedroom_scene

  - id: 7B8BB8E2-A0E4-4F97-95E8-37508C8ABE95
    alias: Bedroom Trigger scene change
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.bedroom_scene
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states.input_select.bedroom_scene.state }}

  - id: F7AD7D3C-7B5C-4690-B4E6-9FCF603A08F1
    alias: good_morning
    initial_state: 'on'
    trigger:
      - platform: time
        at: '06:20'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.huawei_p9_lite
          state: 'home'
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          transition: 600
          brightness: 255
          rgb_color: [255, 126, 0]


