          #################################################
          #     ______      __                            #
          #    / ____/___  / /__________ _____  ________  #
          #   / __/ / __ \/ __/ ___/ __ `/ __ \/ ___/ _ \ #
          #  / /___/ / / / /_/ /  / /_/ / / / / /__/  __/ #
          # /_____/_/ /_/\__/_/   \__,_/_/ /_/\___/\___/  #
          #                                               #
          #################################################


#########################    OBJECTS    #########################

light:

  - platform: mqtt
    name: entrance
    command_topic: "cmnd/sonoff_entrance/power"
    state_topic: "stat/sonoff_entrance/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"


#########################    VARIABLES    #########################

timer:
  entrance_off:
    duration: '00:05:00'

#########################    SCRIPTS    #########################

script:

  entrance_light_on_15_minutes:
    alias: Turn on the Entrance for 15 Minutes
    sequence:
      - service: light.turn_on
        entity_id: light.entrance
      - service: timer.start
        data:
          entity_id: timer.entrance_off
          duration: '00:15:00'

#########################    AUTOMATIONS    #########################

automation:

  - id: B7909331-D503-48C5-A3EA-E098DB725487
    alias: turn off timer expires
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.entrance_off
    action:
      - service: light.turn_off
        entity_id: light.entrance
 
  - id: C9FC5CEF-C6D4-4C15-9E86-06D1DD94A9D6
    alias: come home inside
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: group.phil_devices
      from: 'not_home'
      to: 'home'
    condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    action:
    - service: script.turn_on
      data:
        entity_id: script.entrance_light_on_15_minutes

  - id: 14C4D1D2-574E-4C77-A708-3C5236BB81F2
    alias: turn on entrance when door opens
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    action:
    - service: light.turn_on
      entity_id: light.entrance

  - id: 22EDA51B-E555-4AAD-A67D-8BB5293566D6
    alias: front door closes
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'on'
      to: 'off'
    condition:
    - condition: state
      entity_id: light.entrance
      state: 'on'
    action:
    - service: timer.start
      data:
        entity_id: timer.entrance_off
        duration: '00:05:00'

  - id: 90FC053E-1A56-4AD9-998B-B53183FFDDE3
    alias: goodbye button pressed
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.entrance_button
        click_type: single
    action:
    - service: timer.start
      entity_id: timer.goodbye

  - id: 0CDFFF09-3A2C-4FC7-8419-B8BD250BDCB7
    alias: goodbye button pressed
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.entrance_button
        click_type: single
    action:
    - service: light.turn_on
      entity_id: light.entrance
    - service: light.turn_off
      entity_id: group.goodbye_lights
    - service: timer.start
      entity_id: timer.goodbye
    - service: climate.set_operation_mode
      data:
        entity_id: climate.lounge_ac
        operation_mode: 'off'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.bedroom_ac
        operation_mode: 'off'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.study_ac
        operation_mode: 'off'
    - service: media_player.turn_off
      data:
        entity_id: media_player.samsung_tv_remote
    # - service: script.turn_on
    #   data:
    #     entity_id: script.going_out
    - service: media_player.turn_off
      data:
        entity_id: media_player.smart_ir_tv
