          #####################################
          #    ________      __          __   #
          #   / ____/ /___  / /_  ____ _/ /   #
          #  / / __/ / __ \/ __ \/ __ `/ /    #
          # / /_/ / / /_/ / /_/ / /_/ / /     #
          # \____/_/\____/_.___/\__,_/_/      #
          #                                   #
          #####################################


#########################    VARIABLES    #########################

timer:
  goodbye:
    duration: '00:02:00'

input_boolean:
  bedtime:
    name: In Bed
    initial: 'off'

#########################    SCRIPTS    #########################

script:
  bedtime:
    alias: Goodnight
    sequence:
      - service: light.turn_off
        data:
          entity_id: group.lights_bedtime
      - service: climate.set_operation_mode
        data:
          entity_id: climate.carrier
          operation_mode: 'off'
      - service: media_player.turn_off
        data:
          entity_id: media_player.samsung_tv_remote
  
  going_out:
    alias: Goodbye
    sequence:
      - service: light.turn_off
        data:
          entity_id: group.inside_lights
      - service: climate.set_operation_mode
        data:
          entity_id: climate.carrier
          operation_mode: 'off'
      - service: media_player.turn_off
        data:
          entity_id: media_player.samsung_tv_remote
  
#########################    AUTOMATIONS    #########################

automation:

  - id: E61D107C-8B73-4113-BDC6-2A4565C8401F
    alias: goodbye timer expires
    trigger:
    - platform: state
      event_type: timer.finished
      event_data:
        entity_id: timer.goodbye
    action:
    - service: script.turn_on
      data:
        entity_id: script.going_out
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedtime

  - id: 
    alias: wake up time
    trigger:
    - platform: sun
      event: sunrise
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedtime