          #####################################
          #    ________      __          __   #
          #   / ____/ /___  / /_  ____ _/ /   #
          #  / / __/ / __ \/ __ \/ __ `/ /    #
          # / /_/ / / /_/ / /_/ / /_/ / /     #
          # \____/_/\____/_.___/\__,_/_/      #
          #                                   #
          #####################################


#########################    VARIABLES    #########################

timer:
  goodbye:
    duration: '00:02:00'

input_boolean:
  bedtime:
    name: In Bed
    initial: 'off'

#########################    SCRIPTS    #########################

script:
  bedtime:
    alias: Goodnight
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom
          brightness_pct: 10
          rgb_color: [255, 0, 0] 
      - service: light.turn_off
        data:
          entity_id: group.lights_bedtime
      - service: climate.set_operation_mode
        data:
          entity_id: climate.carrier
          operation_mode: 'off'
      - service: media_player.turn_off
        data:
          entity_id: media_player.smart_ir_tv
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedtime

  
  going_out:
    alias: Goodbye
    sequence:
      - service: light.turn_off
        data:
          entity_id: group.inside_lights
      - service: climate.set_operation_mode
        data:
          entity_id: climate.carrier
          operation_mode: 'off'
      - service: light.turn_on
        data_template:
          entity_id: light.front
          brightness_pct: 100

  new_day:
    alias: reset_each_day
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.j_single_options
          option: j_living_room_1
      - service: input_select.select_option
        data:
          entity_id: input_select.couch_single_options
          option: living_room_select_1
          

  
#########################    AUTOMATIONS    #########################

automation:

  - id: E61D107C-8B73-4113-BDC6-2A4565C8401F
    alias: goodbye timer expires
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.goodbye
    action:
    - service: script.turn_on
      data:
        entity_id: script.going_out

  - id: 243A96FD-97EA-496C-9DEF-846B83F7FB50
    alias: wake up time
    initial_state: 'on'
    trigger:
    - platform: sun
      event: sunrise
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedtime