      #########################################
      #     __ __ _ __       __               #
      #    / //_/(_) /______/ /_  ___  ____   #
      #   / ,<  / / __/ ___/ __ \/ _ \/ __ \  #
      #  / /| |/ / /_/ /__/ / / /  __/ / / /  #
      # /_/ |_/_/\__/\___/_/ /_/\___/_/ /_/   #
      #                                       #
      #########################################

#########################    OBJECTS    #########################

light:
    platform: mqtt
    name: kitchen
    command_topic: "cmnd/sonoff_kitchen/power"
    state_topic: "stat/sonoff_kitchen/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

timer:
  freezer_alert:
    duration: 15

#########################    AUTOMATIONS    #########################

automation:
  - id: 55D54AF9-83B3-4433-990C-EDD0E33930A9
    alias: kitchen switch
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.kitchen_switch
          click_type: single
    action:
      - service: light.toggle
        data_template:
          entity_id: light.kitchen

  - id: 03B27B87-DD0C-430B-BDF1-011BB0A7C9D3
    alias: notify when freezer is left open
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.freezer_door
      to: 'on'
      for: '00:01:00'
    action:
    - service: notify.p_phone_telegram
      data:
        message: Freezer left open

  - id: 0E3650C8-4F50-48CB-A726-11EC1CE9D904
    alias: effect when freezer is open
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.freezer_door
      from: 'off'
      to: 'on'
    action:
    - service: timer.start
      entity_id: timer.freezer_alert

  - id: D6A1CE58-1060-4ADB-9A5F-41DA7E93BBBF
    alias: stop effect when freezer is closed
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.freezer_door
      from: 'on'
      to: 'off'
    action:
    - service: timer.cancel
      entity_id: timer.freezer_alert

  - id: 297DFEC5-271A-4FB6-B8B3-DB6F08A3FF7B
    alias: Alert timer Expires
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.freezer_alert
    condition:
      - condition: state
        entity_id: light.lounge
        state: 'on'
    action:
    - service: light.turn_on
      entity_id: light.lounge
      data:
        effect: 'Twitter'