          #########################
          #     __          __    #
          #    / /   ____ _/ /_   #
          #   / /   / __ `/ __ \  #
          #  / /___/ /_/ / /_/ /  #
          # /_____/\__,_/_.___/   #
          #                       #
          #########################


#########################    OBJECTS    #########################

light:
  - platform: xiaomi_miio
    name: Lab
    host: 192.168.1.37
    token: !secret light_lab_token
    model: philips.light.bulb

octoprint:
  host: 192.168.1.185
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

camera:
  - platform: mjpeg
    name: Printer Camera
    mjpeg_url: http://192.168.1.185/webcam/?action=stream
    still_image_url: http://192.168.1.185/webcam/?action=snapshot

sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

#########################    SCENES    #########################

scene:
  - name: lab_off
    entities:
      light.lab: off

  - name: lab_low
    entities:
      light.lab:
        state: on
        brightness_pct: 20

  - name: lab_medium
    entities:
      light.lab:
        state: on
        brightness_pct: 60

  - name: lab_high
    entities:
      light.lab:
        state: on
        brightness_pct: 100

#########################    AUTOMATIONS    #########################

automation:
  # Toggle light on switch
  - id: 5EF654AE-7B73-4E0E-ADBB-464ABE5F76A8
    alias: toggle_lab_light
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.lab_switch
        click_type: single
    action:
    - service: light.toggle
      entity_id: light.lab

