          #################################################################
          #     __    _       _                ____                       #
          #    / /   (_)   __(_)___  ____ _   / __ \____  ____  ____ ___  #
          #   / /   / / | / / / __ \/ __ `/  / /_/ / __ \/ __ \/ __ `__ \ #
          #  / /___/ /| |/ / / / / / /_/ /  / _, _/ /_/ / /_/ / / / / / / #
          # /_____/_/ |___/_/_/ /_/\__, /  /_/ |_|\____/\____/_/ /_/ /_/  #
          #                       /____/                                  #
          #################################################################

#########################    OBJECTS    #########################

light:
  - platform: yeelight
    devices:
      192.168.1.33:
        name: lounge1
        transition: 1000
        save_on_change: false
      192.168.1.34:
        name: lounge2
        transition: 1000
        save_on_change: false

  - platform: group
    name: lounge
    entities:
      - light.lounge1
      - light.lounge2

climate:
  - platform: broadlink
    name: Carrier
    host: 192.168.1.50
    mac: !secret braodlink_rm_mini_mac 
    ircodes_ini: 'broadlink_climate_codes/carrier.ini'
    min_temp: 17
    max_temp: 30
    target_temp: 23
    temp_sensor: sensor.temperature_living_room
    default_operation: 'off'
    default_fan_mode: low
    customize:
      operations:
        - 'off'
        - cool
        - heat
        - dry
        - auto
      fan_modes:
        - low
        - medium
        - high
        - auto

media_player:
  - platform: mpd
    name: jukebox_mpd
    host: 192.168.1.26
  - platform: spotify
    client_id: !secret spotify_client_id_ha
    client_secret: !secret spotify_client_secret_ha

switch:

  - platform: wake_on_lan
    name: wake_jukebox
    mac_address: !secret mac_jukebox
    turn_off:
      service: shell_command.turn_off_jukebox

  - platform: template
    switches:
      jukebox_power:
        value_template: "{{ is_state ('device_tracker.jukebox', 'home') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.wake_jukebox
        turn_off:
          service: shell_command.turn_off_jukebox
        icon_template: >-
          mdi:music

shell_command:
  turn_off_jukebox: 'ssh hass@192.168.1.26 sudo poweroff'

#########################    STATE VARIABLES    #########################

input_select:
  living_room_colour:
    name: living room colour
    initial: living_room_select_1
    options:
      - living_room_select_1
      - living_room_select_2
      - living_room_select_3
      - living_room_select_4
      - living_room_select_5
      - living_room_select_6

  living_room_lux:
    name: living room brightness
    initial: living_room_high
    options:
      - living_room_low
      - living_room_medium
      - living_room_high

  couch_single_options:
    name: couch single
    initial: living_room_select_1
    options:
      - living_room_select_1
      - living_room_dinner
      - living_room_movie
      - living_room_music
      - living_room_sunset
      - living_room_select_6

#########################    BOOLEANS    #########################

input_boolean:

  sauce:
    name: Quality time
    initial: 'off'
 
#################   SCENES    #################

scene:
  - name: living_room_movie
    entities:
      light.lounge:
        state: on
        brightness_pct: 10
        rgb_color: [102, 108, 255]

  - name: living_room_dinner
    entities:
      light.lounge:
        state: on
        brightness: 158
        rgb_color: [255,145,108]

  - name: living_room_music
    entities:
      light.lounge:
        state: on
        brightness_pct: 100
        rgb_color: [0, 0, 255]

  - name: living_room_cheese
    entities:
      light.lounge:
        state: on
        brightness_pct: 30
        rgb_color: [255, 0, 128]

  - name: living_room_sunset
    entities:
      light.lounge:
        state: on
        brightness_pct: 50
        rgb_color: [255,63,0]

  - name: living_room_select_1
    entities:
      light.lounge:
        state: on
        rgb_color: [255,228,205]

  - name: living_room_select_2
    entities:
      light.lounge:
        state: on
        rgb_color: [0,255,0]

  - name: living_room_select_3
    entities:
      light.lounge:
        state: on
        rgb_color: [0,0,255]

  - name: living_room_select_4
    entities:
      light.lounge:
        state: on
        rgb_color: [255,0,0]

  - name: living_room_select_5
    entities:
      light.lounge:
        state: on
        rgb_color: [255,63,0]

  - name: living_room_select_6
    entities:
      light.lounge:
        state: on
        rgb_color: [80,0,80]

  - name: living_room_off
    entities:
      light.lounge: off

  - name: living_room_low
    entities:
      light.lounge:
        state: on
        brightness_pct: 20

  - name: living_room_medium
    entities:
      light.lounge:
        state: on
        brightness_pct: 60

  - name: living_room_high
    entities:
      light.lounge:
        state: on
        brightness_pct: 100

#################   SCRIPTS    #################

script:

  sauce:
    alias: Cheese
    sequence:
      -  service: media_player.select_source
         data: 
           entity_id: media_player.spotify
           source: jukebox
      -  service: media_player.play_media
         data:
           entity_id: media_player.spotify
           media_content_type: playlist
           media_content_id: spotify:user:ci5uaf6f7eb3incloais4h4zn:playlist:4MR4x8G3XvcKcF4cnLPhgd
      - service: light.turn_off
        entity_id: light.kitchen
      - service: light.turn_off
        entity_id: light.entrance
      - service: light.turn_on
        data:
          entity_id: light.lounge
          brightness_pct: 30
      - service: input_select.select_option
        data:
          entity_id: input_select.living_room_colour
          option: "living_room_select_4"

#################   AUTOMATIONS    #################

#######################################################################################################
#     __    _       __    __                          __   _____         _ __       __                #
#    / /   (_)___ _/ /_  / /______   ____ _____  ____/ /  / ___/      __(_) /______/ /_  ___  _____   #
#   / /   / / __ `/ __ \/ __/ ___/  / __ `/ __ \/ __  /   \__ \ | /| / / / __/ ___/ __ \/ _ \/ ___/   #
#  / /___/ / /_/ / / / / /_(__  )  / /_/ / / / / /_/ /   ___/ / |/ |/ / / /_/ /__/ / / /  __(__  )    #
# /_____/_/\__, /_/ /_/\__/____/   \__,_/_/ /_/\__,_/   /____/|__/|__/_/\__/\___/_/ /_/\___/____/     #
#         /____/                                                                                      #
#######################################################################################################

automation:

      #####   WALL SWITCH   #####

          ########
          # LEFT #
          ########

  - id: 1EE15AC8-0BEE-4B66-B1FD-6A705CA8DDE5
    alias: Living room left switch
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.living_room_wall_left
          click_type: single
    condition:
      - condition: state
        entity_id: light.lounge
        state: 'on'
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.lounge
          
  - id: FDE59D23-5530-4129-84E7-7BECCD39B9DF
    alias: Living room left switch
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.living_room_wall_left
          click_type: single
    condition:
      - condition: state
        entity_id: light.lounge
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.lounge
          rgb_color: [255,228,205]
          brightness_pct: 100

          #########
          # RIGHT #
          #########

  - id: 89B0CB35-A75B-4EA9-AD5E-93A71C9D1EC7
    alias: Livingroom Colour Change
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.living_room_wall_right
          click_type: single
    condition:
      - condition: state
        entity_id: light.lounge
        state: 'on'
    action:
      - service: input_select.select_next
        entity_id: input_select.living_room_colour

  - id: 60AA5F5E-E29C-4DF7-BB92-240EFC3A0537
    alias: Living Room Trigger Colour Change
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.living_room_colour
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states.input_select.living_room_colour.state }}

          #######
          # BOTH #
          ########

  - id: 33F0265A-CF0C-4FA2-B77E-D04E0BE6C55C
    alias: Livingroom Brightness Change
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.living_room_wall_both
          click_type: both
    condition:
      - condition: state
        entity_id: light.lounge
        state: 'on'
    action:
      - service: input_select.select_next
        entity_id: input_select.living_room_lux

  - id: A22EBE05-AF5B-40A8-8F4B-E9191ACBDC2F
    alias: Living Room Trigger Brightness Change
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.living_room_lux
    action:
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states.input_select.living_room_lux.state }}

      #####   BUTTON   #####

  - id: C5C38AE2-C3FB-4AB8-BCD4-8298F23F888B
    alias: Livingroom button single
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.lounge_button
          click_type: single
    action:
      - service: input_select.select_next
        entity_id: input_select.couch_single_options
      - service: scene.turn_on
        data_template:
          entity_id: scene.{{ states.input_select.couch_single_options.state }}

  - id: 93B6E478-4933-4FE3-91FE-D946265D9837
    alias: Livingroom button double
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.lounge_button
          click_type: double
    action:
      - service: switch.toggle
        entity_id: switch.living_room_aircon_power

  - id: 9FA04F90-6F40-4E68-8817-B511E6487D99
    alias: Livingroom button hold
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.lounge_button
          click_type: long_click_press
    condition:
      - condition: state
        entity_id: light.lounge
        state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.sauce

#########################################
#    _________                 __       #
#   / ____/ (_)___ ___  ____ _/ /_____  #
#  / /   / / / __ `__ \/ __ `/ __/ _ \  #
# / /___/ / / / / / / / /_/ / /_/  __/  #
# \____/_/_/_/ /_/ /_/\__,_/\__/\___/   #
#                                       #
#########################################

  - id: BA8A23FA-99DE-4880-A1DE-B11903E219A4
    alias: come home aircon
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: group.phil_devices
      from: 'not_home'
      to: 'home'
    condition:
    - condition: numeric_state
      entity_id: sensor.temperature_living_room
      above: '24'
    action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.carrier
        operation_mode: 'cool'

# If the back door is left open for 3 minutes, turn off the aircon
  - id: BA8A23FA-99DE-4880-A1DE-B11903E219A4
    alias: door open aircon
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      from: 'off'
      to: 'on'
      for: '00:03:00'
    action:
    - service: climate.set_operation_mode
      data_template:
        entity_id: climate.carrier
        operation_mode: 'off'