######################################################################
#      __  ___      _          ______         _____       _ __       #
#     /  |/  /___ _(_)___     / ____/___     / ___/__  __(_) /____   #
#    / /|_/ / __ `/ / __ \   / __/ / __ \    \__ \/ / / / / __/ _ \  #
#   / /  / / /_/ / / / / /  / /___/ / / /   ___/ / /_/ / / /_/  __/  #
#  /_/  /_/\__,_/_/_/ /_/  /_____/_/ /_/   /____/\__,_/_/\__/\___/   #
#                                                                    #
######################################################################

#################   OBJECTS    #################

# binary_sensor.mes_button:
#   name:
#   platform: xiaomi_aqara
#   unique_id: status158d0001e5c0de

light:
  - platform: xiaomi_miio
    name: mes
    host: 192.168.1.39
    token: !secret light_mes_token
    model: philips.light.bulb

switch:
  - platform: mqtt
    name: mes_extractor
    command_topic: "cmnd/sonoff_mes_fan/power"
    state_topic: "stat/sonoff_mes_fan/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

#################   VARIABLES    #################

input_boolean:
  
  mes_dim:
    name: Direction of light brightness control
    initial: 'off'

#################   SCRIPTS    #################

script:

  dim_light_mes:
    sequence:
    - condition: state
      entity_id: input_boolean.mes_dim
      state: 'on'
    - service: light.turn_on
      entity_id: light.mes
      data_template:
        brightness: '{{states.light.mes.attributes.brightness - 10}}'
    - service: script.turn_off
      entity_id: script.dim_light_mes
    - service: script.turn_on
      entity_id: script.dim_light_mes

  brighten_light_mes:
    sequence:
    - condition: state
      entity_id: input_boolean.mes_dim
      state: 'off'
    - service: light.turn_on
      entity_id: light.mes
      data_template:
        brightness: '{{states.light.mes.attributes.brightness + 10}}'
    - service: script.turn_off
      entity_id: script.brighten_light_mes
    - service: script.turn_on
      entity_id: script.brighten_light_mes


#################   AUTOMATIONS    #################

automation:

#########################    EVENTS    #########################
#       single - light on/off                                  #
#       double - light & extractor fan                         #
#       hold - brightness (up then down)                       #
#       long_click_press - null                                #
#       long_click_release - null                              #
################################################################

#########################    SINGLE    #########################

# Single Press, turn the MES light on
  - id: 5CACCCC2-B098-4BAC-9B97-519C2F7CC056
    alias: MES single switch
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.mes_button
          click_type: single
    action:
      - service: light.toggle
        data_template:
          entity_id: light.mes

# # If it's after bedtime, turn the brightness down and set the dim direction up
  - id: ABD330D0-FB2F-4A59-A2FF-253351C287EC
    alias: MES on after bedtime
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: light.mes
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'on'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.mes
        brightness_pct: 5
    - service: input_boolean.turn_off
      entity_id: input_boolean.mes_dim

# # If it's before bedtime, turn the brightness up and set the dim direction down
  - id: AE70F85B-73C5-4F62-A7C7-EDD3D6B3E7F5
    alias: MES on not bedtime
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.mes
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.mes
          brightness_pct: 100
      - service: input_boolean.turn_on
        entity_id: input_boolean.mes_dim


#########################    DOUBLE    #########################
#double tap the switch to turn on/off the light and the extractor

  # Light: On, Extractor On -> Turn both off
  - id: D0024DB8-381D-4BCC-BBD8-865AD263D39F
    alias: MES double switch 11
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.mes_button
          click_type: double
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: light.mes
        state: 'on'
      - condition: state
        entity_id: switch.mes_extractor
        state: 'on'
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.mes
      - service: switch.turn_off
        data_template:
          entity_id: switch.mes_extractor

  # Light: Off, Extractor Off -> Turn both on
  - id: 8B9FB2A3-DD4C-47F2-AE1E-745C6148CCA1
    alias: MES double switch 00
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.mes_button
          click_type: double
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: light.mes
        state: 'off'
      - condition: state
        entity_id: switch.mes_extractor
        state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.mes
      - service: switch.turn_on
        data_template:
          entity_id: switch.mes_extractor

  # Light: On, Extractor Off -> Turn both on
  - id: 55D3C330-B8BB-4E95-9183-AACCFC2C1E69
    alias: MES double switch 10
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.mes_button
          click_type: double
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: light.mes
        state: 'on'
      - condition: state
        entity_id: switch.mes_extractor
        state: 'off'
    action:
      - service: switch.turn_on
        data_template:
          entity_id: switch.mes_extractor

  # Light: Off, Extractor On -> Turn both off
  - id: 44471FDC-FC04-4693-AC02-DB6FBF6B46EC
    alias: MES double switch 01
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.mes_button
          click_type: double
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: light.mes
        state: 'off'
      - condition: state
        entity_id: switch.mes_extractor
        state: 'on'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: switch.mes_extractor

#########################    HOLD    #########################

  - id: 19434725-502A-448D-A587-BE6E50D97626
    alias: xiaomi mes brighten on
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.mes_button
          click_type: long_click_press
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.mes_dim
        state: 'off'
      - condition: state
        entity_id: light.mes
        state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.brighten_light_mes
        
  - id: 9FE65A25-B04E-45FF-8FBF-67AD684DED0D
    alias: xiaomi mes brighten off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.mes_button
        from: 'on'
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.mes_dim
        state: 'off'
      - condition: state
        entity_id: light.mes
        state: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.mes_dim
      - service: script.turn_off
        entity_id: script.brighten_light_mes
   
  - id: A2572C53-B17F-4763-939E-C67E5202259C     
    alias: xiaomi mes dim on
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.mes_button
          click_type: long_click_press
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.mes_dim
        state: 'on'
      - condition: state
        entity_id: light.mes
        state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.dim_light_mes

  - id: 10FBFA14-BE6D-44DA-90A5-0D6E54F62174
    alias: xiaomi mes brighten off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.mes_button
        from: 'on'
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.mes_dim
        state: 'on'
      - condition: state
        entity_id: light.mes
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mes_dim
      - service: script.turn_off
        entity_id: script.dim_light_mes        

#########################    OTHER    #########################

#if just the light is on for 1 minute, turn on the extractor as well
  - id: 482DC948-DE01-42AB-BDCB-FD6D531F5138
    alias: MES light on for a period
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: light.mes
      to: 'on'
      for: '00:01:30'
    condition:
      - condition: state
        entity_id: switch.mes_extractor
        state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.mes_extractor

#if the light is off but the extractor is on, turn off the extractor after 3 minutes
  - id: C91815B5-4C4C-4B86-B044-B6C5DA1BDEFC
    alias: MES light off for a period
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: light.mes
      to: 'off'
      for: '00:03:00'
    action:
      service: switch.turn_off
      entity_id: switch.mes_extractor