          ###############################
          #    ____  _________          #
          #   / __ \/ __/ __(_)_______  #
          #  / / / / /_/ /_/ / ___/ _ \ #
          # / /_/ / __/ __/ / /__/  __/ #
          # \____/_/ /_/ /_/\___/\___/  #
          #                             #
          ###############################

#########################    OBJECTS    #########################

light:
  - platform: xiaomi_miio
    name: office
    host: 192.168.1.35
    token: !secret light_study_token
    model: philips.light.bulb

#########################    SCENES    #########################

scene:
  - name: office_off
    entities:
      light.office: off

  - name: office_low
    entities:
      light.office:
        state: on
        brightness_pct: 20

  - name: office_medium
    entities:
      light.office:
        state: on
        brightness_pct: 60

  - name: office_high
    entities:
      light.office:
        state: on
        brightness_pct: 100

#########################    AUTOMATIONS    #########################

automation:
  # Toggle light on switch
  - id: 5EF654AE-7B73-4E0E-ADBB-464ABE5F76A8
    alias: toggle_office_light
    initial_state: 'on'
    trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.office_switch
        click_type: single
    action:
    - service: light.toggle
      entity_id: light.office

  - id: 731952F9-1A83-4505-8DE7-984B3C0B0276
    alias: bedtime aircon notification
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      from: 'off'
      to: 'on'
    condition:
    - platform: state
      entity_id: binary_sensor.office_aircon
      state: 'on'
    action:
    - service: notify.p_phone_telegram
      data:
        message: "You forgot to turn off the office aircon"



