          #############################################
          #     ____                                  #
          #    / __ \____ _______________ _____ ____  #
          #   / /_/ / __ `/ ___/ ___/ __ `/ __ `/ _ \ #
          #  / ____/ /_/ (__  |__  ) /_/ / /_/ /  __/ #
          # /_/    \__,_/____/____/\__,_/\__, /\___/  #
          #                             /____/        #
          #############################################

#########################    OBJECTS    #########################

light:
  - platform: xiaomi_miio
    name: passage
    host: 192.168.1.40
    token: !secret light_passage_token
    model: philips.light.bulb
  

#########################    AUTOMATIONS    #########################

automation:

  # - id: 097CCD26-9F3D-4EEA-98E2-CCC7448A375E
  #   alias: turn on motion is detected
  #   initial_state: 'on'
  #   trigger:
  #   - platform: state
  #     entity_id: binary_sensor.passage_motion
  #     from: 'off'
  #     to: 'on'
  #   condition:
  #   - condition: state
  #     entity_id: sun.sun
  #     state: below_horizon
  #   action:
  #   - service: light.turn_on
  #     data_template:
  #       entity_id: light.passage
  #       brightness_pct: >-
  #         {% if is_state('input_boolean.bedtime', 'on') %}
  #           {{ 10 }}
  #         {% else %}
  #           {{ 100 }}
  #         {% endif %}


  - id: 6096EF7C-8F7C-4507-8976-720BC2FE64AF
    alias: passage on after bedtime
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.passage_motion
      from: 'off'
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: time
        after: '22:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.passage
          brightness_pct: 100
          color_temp: 333
      # - service: light.turn_on
      #   data:
      #     entity_id: light.bathroom

  - id: 124CA256-2678-4428-81C9-3F3F5B3A3300
    alias: passage on before bedtime
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.passage_motion
      from: 'off'
      to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: time
        before: '22:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.passage
          brightness_pct: 100
          color_temp: 333
      # - service: light.turn_on
      #   data:
      #     entity_id: light.bathroom

  - id: 87A188FB-0A93-400B-AD18-A86BB1D0EA25
    alias: turn off when no motion is detected
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.passage_motion
      from: 'on'
      to: 'off'
    condition:
    - condition: state
      entity_id: light.passage
      state: 'on'
    action:
    - service: light.turn_off
      entity_id: light.passage